### ISSUE TITLE
Nothing but syntactical highlighting working on v 3.1.1 build 3176

### ISSUE THREAD

**Issue by guricchio** [cdgramos/Sublime-Text-3---HL7-Plug-In#20]
Inspector, Search, Cleaner greyed out.

Status bar not working and so on

![image](https://user-images.githubusercontent.com/45463573/53893337-a0ddbd00-3ff3-11e9-9b75-ab9785483f15.png)

**Comment by cdgramos** [comment]
Thanks for reporting.  Version 3.1.1 build 3176 is the one I'm using to develop the plug-in and it has been working good so far, so the version isn't the issue here. I'll try to reproduce this issue and I'll get back to you as soon as I can.

**Comment by cdgramos** [comment]
The project structure wasn't compatible with package control. The structure have been changed to be in conformance with package control. Please refer to the installation instructions on repo readme.md
