### ISSUE TITLE
HL7 Cleaner needs refinement

### ISSUE THREAD

**Issue by joshsyapse** [cdgramos/Sublime-Text-3---HL7-Plug-In#24]
HL7 Cleaner could use some refinement.  It is looking for segment names but should maybe look for the segment name and a preceding  end of segment character.  This will avoid treating the NTE in CENTER or INTERNAL as the start of an NTE segment.  Also seeing things like ACTIVATED creating a CTI segment and HFHS creating a FHS segment.

**Comment by cdgramos** [comment]
Thanks for this, will work on it.

**Comment by cdgramos** [comment]
Test message that was used:
MSH|^~\&|AA|Z0|BB|Z0|199908180016||ADT^A04^ADT_A04|ADT.1.1698593|P|2.5.1|PID|1||000395122||ACTIVATED^CENTER^C||19880517180606|M|||Happy \& Cute Street&Pretty Plaza^^98052~98053||(157)983-3296|||S||12354768|87654321|NK1|1|Janette^Doe^C|HFHS|Happy Street^^98052|(157)883-6176|  AL1|DG1|

The cleaner now works properly.

**Comment by cbgann** [comment]
Seems to still be happening with some segments, noticeably ODT, ORG, NST, ACC, INV.

Sample message used:
MSH|^~\&|EPIC|^LINDAS TEST ORGANIZATION|||||VXU^V04^VXU_V04|225|P|2.5.1||||AL|PID|1||E46749^^^^MR^||DOE^JOHN^C^JR^^^L|SMITH|20140515|M|SMITH^JOHN|2106-3^WHITE^HL70005|115 MAINSTREET^^GOODTOWN^KY^42010^USA^L^010||^PRN^PH^^^270^6009800||EN^ENGLISH^HL70296||||523968712|||2186-5^NOT HISPANIC OR LATINO^HL70012||||||||N|PD1|||LINDAS TEST ORGANIZATION^^SIISCLIENT818|^^^^^^^^^^^^MR|||||||02^Reminder/recall-any method^HL70215|||||A^Active^HL70441|20150202^20150202 NK1|1|DOE^MARY|MTH^MOTHER^HL70063|PV1||R||||||||||||||||||V02^20150202|ORC|RE||9645^SIISCLIENT001||||||20150202111146|2001^HARVEY^MARVIN^K| RXA|0|1|20150202|20150202|20^DTaP^CVX^90700^DTAP^CPT|.5|ML^mL^ISO+||00^New immunization record^NIP001|JONES^MARK|^^^SIISCLIENT818||||A7894-2|20161115|PMC^SANOFI PASTEUR^MVX||||ARXR|ID^INTRADERMAL^HL70162|LD^LEFT DELTOID^HL70163OBX|1|CE|64994-7^VACCINE FUNDING PROGRAM ELIGIBILITY CATEGORY^LN|1| V02^MEDICAID^HL70064||||||F|||20150202|||VXC40^ELIGIBILITY CAPTURED AT THE IMMUNIZATION LEVEL^CDCPHINVSOBX|2|CE|30956-7^VACCINE TYPE^LN|2|88^FLU^CVX||||||F|||20150202102525 OBX|3|TS|29768-9^Date vaccine information statement published^LN|2|20120702||||||FOBX|4|TS|29769-7^Date vaccine information statement presented^LN|2|20120202||||||FRXA|0|1|20141215|20141115|141^influenza, SEASONAL 36^CVX^90658^Influenza Split^CPT|999|||01^HISTORICAL INFORMATION – SOURCE UNSPECIFIED^ NIP001||||||||||||A

**Comment by cdgramos** [comment]
Hello @cbgann, I'll take a look at this in the next days, thanks!
