### ISSUE TITLE
Issues with plugin in ST3

### ISSUE THREAD

**Issue by narenparimi** [cdgramos/Sublime-Text-3---HL7-Plug-In#36]
This plugin is not working anymore. All the features are disabled for right click any thoughts?.
<img width="299" alt="Screen Shot 2020-03-18 at 1 32 42 AM" src="https://user-images.githubusercontent.com/3082054/76932228-69694800-68b8-11ea-9365-09817be30e0e.png">

**Comment by cdgramos** [comment]
Hey, I've tried to reproduce the problem but I couldn't. I've tried in in Sublime Text version 3.2.2. Try to re-install it please.
