### ISSUE TITLE
Segment / Event Search Broken - Alternative URL?

### ISSUE THREAD

**Issue by howardanton** [cdgramos/Sublime-Text-3---HL7-Plug-In#37]
Does anyone have another URL for the Segment / Event Search Inside of hl7tools.py?  Apparently, "http://hl7-definition.caristix.com:9010/HL7%20v2.5.1/Default.aspx?version=HL7v2.5.1&" is no longer secure.  I used this a lot to look at possible options for the various segments and subfields.  Any help would be appreciated.

**Comment by cdgramos** [comment]
Hello!

It should be working now, you will have to update the package. Thanks for noticing!

**Comment by howardanton** [comment]
Thank you.  You've made an amazing plug-in even six years later.
